version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
stack_name = "asa"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qhbingczl7ww"
s3_prefix = "asa"
confirm_changeset = true

