version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\" ChannelType=\"LIFF\""
stack_name = "asaApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qhbingczl7ww"
s3_prefix = "asaApp"
confirm_changeset = true
